@echo off
call "%~dp0\..\DevopsData\config.bat"

set CLIENT_WINDOW_WIDTH=600
set CLIENT_WINDOW_HEIGHT=600
set SERVER_PORT=7778

start "%PROJECT_NAME%-%VERSION% Client" "%CLIENT_EXE_PATH%" -WINDOWED -ResX=%CLIENT_WINDOW_WIDTH% -ResY=%CLIENT_WINDOW_WIDTH% -WinX=10 -WinY=50 -ExecCmds="open 127.0.0.1:%SERVER_PORT%"
start "%PROJECT_NAME%-%VERSION% Client" "%CLIENT_EXE_PATH%" -WINDOWED -ResX=%CLIENT_WINDOW_WIDTH% -ResY=%CLIENT_WINDOW_WIDTH% -WinX=620 -WinY=50 -ExecCmds="open 127.0.0.1:%SERVER_PORT%"